### ISSUE TITLE
Remind interns that no issue is too big or too small to file

### ISSUE THREAD

**Issue by alexkarasik** [open-learning-exchange/open-learning-exchange.github.io#1006]
I wasn't sure if some of the issues I was filing were too insignificant at times, but now in my experience, they have almost all been met with understanding and an approval for a pull request. I think some people may be intimidated at first with not finding significant enough issues to file and may be missing the point of this stage.

I believe a few lines in the opening paragraphs on the issues page that lets interns know that know issue is too big or too small and that they do not necessarily have to make the pull request or solve the problem they filed an issue for will help some understand better what is expected in this stage and why as long as they are descriptive about what the problem actually is.

**Comment by aurinsomnia** [comment]
I do agree for the most part with the premise of this issue. I too struggled initially with issues, because I couldn't find any bugs or "real problems", and felt like making minor grammatical or formatting changes was pointless. That said I don't want to diminish the process to just fixing periods, or spaces etc. If you can find a way to emphasize that these kinds of fixes are acceptable without making it seem like an "easy way out" of the process, then I think this would be a valuable change. Go ahead and make a PR with the changes you wish to make.
