### ISSUE TITLE
BeLL installation in Windows

### ISSUE THREAD

**Issue by ExaMind** [open-learning-exchange/open-learning-exchange.github.io#1208]
According to the installation guide ( http://open-learning-exchange.github.io/#!./pages/installation.md ) to install the community BeLL and its dependencies in your computer you'll just have to copy and paste one of scripts ( depending on your OS) in your command prompt as admin. 

However, this does not work when I tried it. I am using Windows 10 Pro. I get the following error message:
      Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient 
      request."
      At line:1 char:1
      + (New-Object Net.WebClient).DownloadFile('https://raw.githubuserconten ...
      + 
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

I am not sure if anyone else experienced this issue. But what I did to work around this issue was I just downloaded the install.bat file at https://raw.githubusercontent.com/dogi/ole--vagrant-vi/master/windows/install.bat and ran it manually.

I suggest we add this 3rd method just in case some people can't get the script to work.

**Comment by kylemathias** [comment]
@ExaMind I am hesitant to say "go ahead and make the change" because this might of been a problem that you only came across. The fact that you found a work around on your own is great, and makes me lean more towards not adding a 3rd way.

We want to keep the wiki as small as possible. The wiki is already "To big" and needs some trimming.
