### ISSUE TITLE
Helpful reminder to update repository before anything

### ISSUE THREAD

**Issue by lorugant** [open-learning-exchange/open-learning-exchange.github.io#1350]
The note in blue section is very easy to get overlooked. Can we add a line about this in subsequent steps as a quick reminder to keep local repositories and github.io repository updated?

![screenshot from 2017-11-07 14-33-31](https://user-images.githubusercontent.com/32945884/32513637-b64cd8f4-c3c8-11e7-95dc-a01d17917231.png)

Like for example in such steps where we are making changes...
![screenshot from 2017-11-07 14-31-27](https://user-images.githubusercontent.com/32945884/32513502-63ee1f0a-c3c8-11e7-9b68-3fe93c764f41.png)

Please let me know if it is a valid one. Thanks.

**Comment by kylemathias** [comment]
the reason it is in blue is so people don't over look it. It might be more reasonable to assume that new interns should pay more attention to blue Notes rather than for us to state it twice.

If you would like, in the second picture you posted, you can try to condense the blue note and green hint into one useful note. We are always looking for ways to make our first steps more concise. If you can, make a new Issue stating what you are going to do, and then go ahead and make the changes in a new pull request.
