### ISSUE TITLE
Markdown Wiki Reminder

### ISSUE THREAD

**Issue by ofrank23447** [open-learning-exchange/open-learning-exchange.github.io#1459]
I had some trouble in the beginning since I relied on using Markdown preview option to see what I changed on my .md page. 
I added a reminder and an example to future interns to check their changes with rawgit.
On the bottom, I added a section that says "Reminder"
![image](https://user-images.githubusercontent.com/24216313/34855483-cb7f2e0c-f6f4-11e7-87dc-241b95a20b41.png)

**Comment by ofrank23447** [comment]
I fixed that spelling error to Markdown from Markdwon and also placed a what each code is (raw, preview, MDWiki). Ready to PR

**Comment by xyb994** [comment]
- Instead of "Reminder", we better stick with one of [these](http://dynalon.github.io/mdwiki/#!gimmicks.md) alert box since they come with MDwiki, and I believe we  are mostly using `Note:` in our Markdown files.

- It might be a good idea to add some info about Markdown flavors. Something similar to this: As MDwiki site is what we use for "production." Please always check if everything renders as you expected using rawgit link. There are [different flavors of Markdown](https://github.com/commonmark/CommonMark/wiki/Markdown-Flavors). Use GitHub's preview tab for reference only.

- There's already a lot of images on the same page. Instead of embedding the comparison image, what do you think about adding a link to the image?

**Comment by ofrank23447** [comment]
I can do it using Note:
And I will include as you mentioned.
Yes, I believe adding a link is better.
Let me know

**Comment by xyb994** [comment]
Sounds good, open a PR for it so everyone could review.

**Comment by ofrank23447** [comment]
@xyb994 https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1502

**Comment by xyb994** [comment]
@kylemathias @ofrank23447 My main concern is still that this page contain many images already. Since we already delivered the message that GitHub's preview might be different on MDwiki, in the end, the image seems not necessary to me.

**Comment by ofrank23447** [comment]
@kylemathias @xyb994 Then, I can discard the image and combine that Note into one instead. Please let me know
