### ISSUE TITLE
Installation config page streamline

### ISSUE THREAD

**Issue by NickBratt** [open-learning-exchange/open-learning-exchange.github.io#1628]
While looking through the installation configuration page, all the links open into new tabs except the "vagrant instructions" link. This link should open in a new tab. It is also easier to look between two tabs as opposed to going back in forth.

**Comment by xyb994** [comment]
Are you referring to the first note on https://open-learning-exchange.github.io/#!./pages/techgenius/tg-installation.md ?

The option to open a link in a new tab does not seem to be implemented in MDwiki. We would also avoid using HTML because that defects the purpose of using Markdown – having a clean and easy to read/write page.

**Comment by NickBratt** [comment]
Yes there's one at the top of the page and one towards the bottom. All the other links on the page open in a new tab.
