### ISSUE TITLE
https://talk.ole.org not loading

### ISSUE THREAD

**Issue by sahilph** [open-learning-exchange/open-learning-exchange.github.io#1676]
On the page [rbts-intern-orientation.md](http://open-learning-exchange.github.io/#!./pages/robots/rbts-intern-orientation.md) the secure [https version](https://talk.ole.org) of talk.ole.org does not load, but http://talk.ole.org loads fine.

Can someone check whether the webserver is listening on port 443 ?

If there is no https version of the page, the links can be fixed.

**Comment by kylemathias** [comment]
@dogi would have the right answer.

**Comment by dogi** [comment]
@sahilph this is a good one

right now express does not have a certificate
and because of that is not listening to port 443

**Comment by joeadom** [comment]
Don't send me this messages again, remove me from the thread, thank you.

**Comment by sahilph** [comment]
@dogi Oh OK. Since it's just a redirect, can the links be changed to http ?

**Comment by xyb994** [comment]
@sahilph Yes

**Comment by sahilph** [comment]
PR https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1684

**Comment by joeadom** [comment]
Please remove me from the thread. thank you.

**Comment by xyb994** [comment]
Hello @joeadom,

You are receiving notifications most likely because you are "watching" this repository https://github.com/open-learning-exchange/open-learning-exchange.github.io. There's nothing we can do to help you.

- To mute this thread, please follow the link in the original email you received from GitHub.
- To unsubscribe from future activities about this repo, please go to https://github.com/watching and "unwatch" our repo.

Helpful links:
https://help.github.com/articles/watching-and-unwatching-repositories/#unwatching-a-single-repository

**Comment by joeadom** [comment]
I don't have access to the computer I used to create the account. Please
delete my account. Thank you.
Kind regards,
Joseph Adom.

**Comment by xyb994** [comment]
Hi @joeadom,

Please follow these links to reset your password then delete your account:
https://github.com/password_reset
https://help.github.com/articles/deleting-your-user-account/

There nothing else we can do to help you. If you have further questions, please [open a support ticket with GitHub](https://github.com/contact) instead of emailing back and sending four other people notifications that's unrelated to the topic.
