### ISSUE TITLE
Add point to vi-faq.md stating how to see changes made to local repository 

### ISSUE THREAD

**Issue by ManiBlitz** [open-learning-exchange/open-learning-exchange.github.io#1724]
### Problem
It is recurrent to have interns make multiple commits to the same file because they do not know where to see the changes they have made to their local repository. I did not saw any part showing how to do so and supposed it would be great to add it to the FAQ.

### Steps to reproduce the problem
Using the link `file:///[MyPrivatePath]/ManiBlitz.github.io/index.html#!index.md` does not enable to see the files but will redirect to an error 404 page. 

### Screenshots
![Error Message](https://user-images.githubusercontent.com/26188374/38773071-86595782-4012-11e8-9574-7b458990d98d.png)

### Proposed solution
@xyb994 proposed a simple way to access to the local changes. You just need to use the following command from your local repository: `python3 -m http.server`. You will receive this message: `Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...`
Then you can access your local repository from your localhost at port 8000 and see your local changes.

**Comment by xyb994** [comment]
@ManiBlitz 

The way to preview is actually mentioned in this repo's readme https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/README.md#how-to-preview. 

I agree we should add it somewhere in First steps. FAQ might not be the best place since not everyone would look at it. At this time, Step 6 vi-github-issues.md might be the best place since it's the first time we ask prospective interns make changes locally and push them.

**Comment by ManiBlitz** [comment]
I will do then. I even think that providing the link http://dynalon.github.io/mdwiki/#!faq.md directly will be a better idea. I contains every necessary help needed.

**Comment by xyb994** [comment]
@ManiBlitz Yes, http://dynalon.github.io/mdwiki/#!faq.md is a good one. Since this will be fairly short, be sure to make it a little more obvious. Maybe add a `## Preview Changes Locally` section before "Create a Commit"?

**Comment by ManiBlitz** [comment]
For sure. Can I go ahead and make a pull request?

**Comment by xyb994** [comment]
@ManiBlitz Yes, please go ahead.
