### ISSUE TITLE
Summary for Vagrant Tutorial

### ISSUE THREAD

**Issue by rhuturajm** [open-learning-exchange/open-learning-exchange.github.io#1733]
### Problem
Creating a summary for Vagrant Installation 

### Steps to reproduce the problem

N/A

### Screenshots

N/A

### Proposed solution

Summary - 
a) For Windows
1) Install  Vagrant, VirtualBox, Git, and BeLL to your OS using Step 1 - BeLL Installation - Installation
2)Pick your preferred command line program - Git Bash, Command Prompt or Windows Powershell
3)Go to the directory that contains our Vagrantfile: cd C:\Users\YOUR_USERNAME\ole--vagrant-vi
4)Check global status of vagrant : vagrant global-status 
5)Use Vagrant Up to start , Vagrant Suspend to pause, Vagrant Halt to shut down, or Vagrant Destroy to delete the virtual machine
b)For Mac or Linux
1) Install  Vagrant, VirtualBox, Git, and BeLL to your OS using Step 1 - BeLL Installation - Installation
2)Use Terminal and cd where you git clone the ole--vagrant-vi repository in Step 1 - Bell Installation
3)Use Vagrant Up to start , Vagrant Suspend to pause, Vagrant Halt to shut down, or Vagrant Destroy to delete the virtual machine

**Comment by xyb994** [comment]
@rhuturajm Are you suggesting adding the summary to `vi-vagrant.md`? Would you placed it to the start or the end of the page?

**Comment by xyb994** [comment]
`vi-vagrant.md` is meant to give virtual interns an overview of how to use vagrant. At the start of this page, we mentioned "In Step 1 - BeLL Installation - Installation, we installed Vagrant, VirtualBox, Git, and BeLL to our OS." as a recap of previous step. I think the page itself is not long. If you can format the proposed summary better in Markdown, maybe we could add the summary to the start of the page?

**Comment by rhuturajm** [comment]
Yes it makes much more sense if  we add the summary in  vi-github-and-markdown.md as a recap of previous steps. But i feel we should put it above Start Here.
<img width="1309" alt="untitlebjbd" src="https://user-images.githubusercontent.com/38227119/38902566-172a9894-426f-11e8-8c5f-f957a4a0d751.png">

**Comment by xyb994** [comment]
@rhuturajm 

Step 3, 5, 6, 8 are about Git/GitHub and the rest of steps are about BeLL. I don't think it would be a good idea to add BeLL installation and vagrant summary to Step 3.

Sorry if I confused you. What I meant was we can consider adding the summary to the start of Step 2 - Vagrant Instructions. Personally I don't think it's necessary because we already summaried what Step 1 did in the first sentence in Step 2. Step 2 itself is meant to be a quick reference and much of the commands we mention are already on the left side bar. But since you did not format proposed summary in Markdown, I was thinking maybe we can take another look:

---

## Summary

### For Windows

1. Install  Vagrant, VirtualBox, Git, and BeLL to your OS using Step 1 - BeLL Installation - Installation
2. Pick your preferred command line program - Git Bash, Command Prompt or Windows Powershell
3. Go to the directory that contains our Vagrantfile: `cd C:\Users\YOUR_USERNAME\ole--vagrant-vi`
4. Check global status of vagrant : `vagrant global-status`
5. Use `Vagrant Up` to start , `Vagrant Suspend` to pause, `Vagrant Halt` to shut down, or `Vagrant Destroy` to delete the virtual machine

### For Mac or Linux
1. In Step 1, we installed Vagrant, VirtualBox, Git, and BeLL to your OS
2. Use Terminal and `cd` to where you `git clone` the `ole--vagrant-vi` repository
3. Use `Vagrant Up` to start , `Vagrant Suspend` to pause, `Vagrant Halt` to shut down, or `Vagrant Destroy` to delete the virtual machine

---

Personally I still don't think this addition is necessary, but let's see what other interns says about it.

**Comment by rhuturajm** [comment]
Sorry I did not understand what you said in earlier comment but its clear now I will format the proposed summary for markdown tutorial.
