### ISSUE TITLE
Adding more info for Vagrant BeLL

### ISSUE THREAD

**Issue by rhuturajm** [open-learning-exchange/open-learning-exchange.github.io#1734]
### Problem
In the vi-bellapps.md, it would be better if we can add more information on how to go your Vagrant BeLL and then select library to continue the process.

### Steps to reproduce the problem

N/A

### Screenshots

<img width="801" alt="untitvdsvdled" src="https://user-images.githubusercontent.com/38227119/38909742-f301cec2-4293-11e8-98c7-d76c66f93404.png">

### Proposed solution

We have a few minor information to add above "From there, go to your Vagrant BeLL. Select Library from the dashboard and then select Add a Resource."  to make it more clear:
Step 1 - Check your virtual machine is running or not. If not go to your command terminal in windows or terminal in Mac or Linux and cd to your ole--vagrant-vi directory
Step 2 - Start vagrant with vagrant up
Step 3 -  Open your browser (preferrably, Mozilla Firefox) and go to http://127.0.0.1:5985/ to start BeLL-Apps and sign in.

**Comment by ManiBlitz** [comment]
That would be a really useful addition. I was also a little bit confused the first time I was asked to use BeLL App and add resources.

**Comment by rhuturajm** [comment]
so can i generate a pull request?

**Comment by xyb994** [comment]
@ManiBlitz Thank you for the input here.

@rhuturajm I was actually working on updating this page at PR #1692. The link was added but I did not mention `cd`, `vagrant up`, or sign in. It might worth mentioning `vagrant up` if BeLL is not running here. Please do keep in mind that less is more. We ran into the issues that First steps getting too cluttered because of all the info added. 

@ManiBlitz @rhuturajm Please let me know what you think about this version: https://rawgit.com/open-learning-exchange/open-learning-exchange.github.io/update-bell-apps-tutorial/#!pages/vi/vi-bellapps.md

See also [*General Issue* Less is More!](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/1108)

**Comment by rhuturajm** [comment]
Looks better but definitely if we can add a step in there to check vagrant up would be really helpful!

**Comment by xyb994** [comment]
@rhuturajm Please check out the change I just made: https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1692/commits/11d2b486ee330ccd30732054bc619d455e832345
