### ISSUE TITLE
 BeLL-Apps Library

### ISSUE THREAD

**Issue by akshayuncc** [open-learning-exchange/open-learning-exchange.github.io#1800]
### Problem
When ever I search for any resources from the library and click on view details I am able to edit and make changes to the main resource file. I am not the owner or the edit but still I can make those changes. I am not sure if you want it to be editable for everyone but I think this should not be made editable for everyone because of security reasons. Anyone can make changes to anyone's resource. 

### Steps to reproduce the problem
Steps:
1. Login to your Bell MyApp using username and password.
2. Click on library 
3. From any of the available resources click on view details.
4. A new view details page is visible which lets me edit the resource details.

### Screenshots
![image](https://user-images.githubusercontent.com/25532941/40062952-4f418442-582a-11e8-83d4-78babaea0d6c.png)

![image](https://user-images.githubusercontent.com/25532941/40062974-5b0878da-582a-11e8-966b-8aa80bde7884.png)

### Proposed solution

N/A

(I am not sure if it is suppose to be like this but I think there should be some authentication before anyone can change the resource details),

**Comment by xyb994** [comment]
@akshayuncc 

- this is not really the right repo to raise issues about bell.
- you are able to edit detail info of resources because you are signed in as admin, if you create a normal user at login page, you would not be able to see the edit button.
- please note that bell is on feature freeze and we are focus on developing [planet](https://github.com/open-learning-exchange/planet) at this time.
