### ISSUE TITLE
Cannot get back to First Step page if clicked on OLE Support 

### ISSUE THREAD

**Issue by akshayuncc** [open-learning-exchange/open-learning-exchange.github.io#1816]
### Problem
If you are on the first Steps page and click on the OLE Support you will be taken to an index.md page but if you click the back button you will not be able to get back to the First Steps page.

### Steps to reproduce the problem

Go to the First Steps page and click on the OLE Support in the top left corner next to the logo.
Try to click the back button you will not be able to go back to the first steps page.

### Screenshots

![image](https://user-images.githubusercontent.com/25532941/40376159-9b656eb0-5dbb-11e8-9aae-eb4209909023.png)

![image](https://user-images.githubusercontent.com/25532941/40376178-a3cea74c-5dbb-11e8-9885-7ab4b8f462f7.png)

### Proposed solution

N/A
(Working on it)

**Comment by xyb994** [comment]
It worked fine for me on Chrome. It's more like a browser issue, looks like the problem is it goes to
https://open-learning-exchange.github.io/#
then
https://open-learning-exchange.github.io/#!index.md

Do you plan to change MDwiki's JavaScript somewhere so it goes to https://open-learning-exchange.github.io/#!index.md directly? 

Please focus on raising issue about the content of our MDwiki.

**Comment by akshayuncc** [comment]
By raising issues about MdWiki do you mean issues related to the First Steps Page?

**Comment by xyb994** [comment]
I mean the actually content of http://open-learning-exchange.github.io

**Comment by akshayuncc** [comment]
Sure @xyb994 I will try and raise as many issues as possible. 
Thank you.

**Comment by gowiredu** [comment]
@xyb994 @akshayuncc Is this issue by any chance closed?

**Comment by gowiredu** [comment]
It looks to me like it might be but it's still under the "Open" issues.
