### ISSUE TITLE
Redundant Text in macOS "BeLL Installation" Instructions in Step 1

### ISSUE THREAD

**Issue by gowiredu** [open-learning-exchange/open-learning-exchange.github.io#1898]
### Problem
Redundant text in macOS "BeLL Installation" instructions in Step 1.

In the first screenshot, 

> "For macOS and Ubuntu – Install a Community BeLL"

could just read

> "Install a Community BeLL"

since it's already under the general _"macOS or Ubuntu"_ instructions.

Having it read

> "For macOS and Ubuntu – Install a Community BeLL"

might confuse aspiring interns for a moment.

### Steps to reproduce the problem
N/A

### Screenshots
![gowiredu-issue-5](https://user-images.githubusercontent.com/10681719/41738218-7aecd8a6-755f-11e8-9f90-796be531b49a.png)

### Proposed solution
Change

> "For macOS and Ubuntu – Install a Community BeLL"

to

> "Install a Community BeLL"

**Comment by xyb994** [comment]
I add the extra text so prospective virtual interns do not get confused about which platform "Install a Community BeLL" is for, it's far away from the header "macOS or Ubuntu".

Since this kind of confuses you to raise issue #1897, what do you think about adding a "Preparation" header right after "macOS or Ubuntu", so "For macOS" and "For Ubuntu" could be smaller and "Install a Community BeLL" would stand out more?

**Comment by gowiredu** [comment]
That should work. I'll make the edits.
