### ISSUE TITLE
Virtual Intern MDWiki Step 6 Clarification

### ISSUE THREAD

**Issue by Vncentou422** [open-learning-exchange/open-learning-exchange.github.io#1907]
### Problem
Clarify that the interns are able to resolve a separate issue that is not their own to satisfy the Step 6 requirement. Also clarify that they must comment on an existing issue that is not their own before they proceed. 

### Steps to reproduce the problem
N/A

### Screenshots
<img width="878" alt="screen shot 2018-06-26 at 2 31 48 am" src="https://user-images.githubusercontent.com/5431055/41893367-87d63a8e-78e9-11e8-8b21-64b4d12dbe81.png">

### Proposed solution
Make sure you have created at least one issue, resolved it (or a separate issue that is not your own), commented on an existing issue and have a pull request with the fix merged before proceeding to the next step.

**Comment by xyb994** [comment]
@Vncentou422 For step 6, we are walking through the process of creating an issue, making commits, and creating PR. I think it's better to have prospective virtual intern come up with their own issue at this stage. But we can probably add somewhere in step 8 that they are able to fix some existing issues upon checking with us.

I'm ok with emphasizing commenting on other issue since it tend to get ignored.
