### ISSUE TITLE
simpleinstall.md is empty

### ISSUE THREAD

**Issue by efrencortes315** [open-learning-exchange/open-learning-exchange.github.io#192]
Currently there is a link under the "Teams" tab called "Simple Install".  This loads up an empty page, due to the fact that http://open-learning-exchange.github.io/#!pages/simpleinstall.md does not exist.

I'm unsure what the original purpose of this page is, so if I can receive more information about the "simple install' I can create a page for it or we can simply remove the link for the menu.

**Comment by DrewPerlman** [comment]
The MD pages under the Teams tab are meant to provide instructions to the interns of what they will be doing each week with their teams. The Team pages are a work-in-progress, so that's why some of them are unorganized or missing information.

I'll go ahead and link the Google Docs with the instructions for each team at the top of each page.
