### ISSUE TITLE
GUI demonstration of some CMD 

### ISSUE THREAD

**Issue by kholood-ea** [open-learning-exchange/open-learning-exchange.github.io#2118]
### Steps to reproduce the problem

providing alternative GUI aproceh for some of the steps can be helpful for getting since of whats happening  

### Screenshots

N/A

### Proposed solution

For example this : 

-git clone https://github.com/open-learning-exchange/planet.git
-cd planet
-vagrant up prod

we can take screenshots of manually downloading the zip file from the Github, then manually creating a new folder and so on

**Comment by jazdao** [comment]
Hi @kholood-ea, I agree that it could be useful to have an alternative GUI approach for some of the steps, but I think that the page would get a bit cluttered if both methods were included.  For the most part though, I believe Step 3 and Step 5 do provide instructions for using Git through the interface instead of the command-line.

**Comment by lmmrssa** [comment]
@kholood-ea Our intend is to make people familiar with CLI of Git as that will work for all platform and we are just teaching basic level there is a lot we can do on git.. For GUI you you can always follow to related websites. So we have also links for websites, where can learn more about git.

**Comment by kholood-ea** [comment]
@jazdao 
@lmmrssa 
 I can see your points and I agree 

its just that at first I got mixed up a little with all those commands with no sense of whats happening so I thought to bring this suggestion up, but no worries.
