### ISSUE TITLE
Add Further Explanation on Editing Local Files for Step 6

### ISSUE THREAD

**Issue by YuserahN** [open-learning-exchange/open-learning-exchange.github.io#2140]
### Problem
This is only a minor issue, but it might help improve Step 6. 
As displayed in the screenshot below, after walking us through creating a new branch using git, it simply states, "Now you can go and make the proposed changes to your local files.' While that's self-explanatory, it might be helpful to list a few ways to open a local file using commands in the command prompt and Git Bash. 

### Steps to reproduce the problem

N/A 

### Screenshots

![image](https://user-images.githubusercontent.com/21087353/51860508-90a13680-22ff-11e9-9193-1565e392e438.png)

### Proposed solution
 
This note could be added: 
**NOTE:** While you can open the file locally from the file explorer, you can also open it using commands in Git Bash and Windows Command Prompt. You can cd into the correct directory and use ```start <filename>``` to open the file for editing. In the Windows Command Prompt, you can also simply type in the filename to open it. You can open it using any text editor that you prefer. Using ```cat <filename>``` in Git Bash, you can also view the contents of the file within the terminal.

**Comment by lmmrssa** [comment]
Not sure if we want this to be worked on. As people will prefer different IDE to work on local files. Also purpose of these steps is to make VI familiar with skill sets required to work on real project. And there will be requirement to change lot of files when working on that. So person will not prefer to look in terminal for files.

NOTE: If you want to guide user on ways to work on local files then try to mention that they can use any IDE they prefer to edit local file. Also they can use VIM or Nano to edit files from terminal. Then you can add link official guide of VIM or Nano instead of writing everything in the page.

**Comment by YuserahN** [comment]
@lmmrssa Thank you for reviewing this issue. Should I go ahead and create a pull request for the changes you've suggested?
