### ISSUE TITLE
Step 6 - Issuse :Forced to reconfigure VM after running 'vagrant ssh {name}' command in Step 2

### ISSUE THREAD

**Issue by briighter** [open-learning-exchange/open-learning-exchange.github.io#2202]
### Problem
After clicking into [Step 2 - Planet and Docker](http://open-learning-exchange.github.io/#!./pages/vi/vi-docker-tutorial.md), I am tasked to enter the `vagrant ssh {VM name}` into Git Bash in windows in the Planet folder, the CLI executes a docker container. After the container is built, we are tasked with running docker commands. After writing the command to spawn the environment for the first time `docker-compose -f planet.yml -p planet up -d --build`, the localhost:3100 sends the user to the configuration page and the user must reconfigure their Planet accounts. When attempting to create an account you are prompted with an error that an account cannot be created. Then exiting the Docker & Planet back to the Git Bash I was able to enter the login page as normal.

### Steps to reproduce the problem

Steps to recreate the problem were stated above and I attempted to recreate the problem and there seems to be no symptoms.

### Screenshots

N/A

### Proposed solution

N/A

**Comment by lmmrssa** [comment]
@briighter Steps in Planet and Docker are there to make you familiar with docker technology. Vagrant is already running docker inside it which is running planet application.
Running docker-compose up will create another instance of planet that's why you were asked to create new configuration. Also you can not create two configuration with same community name. That's why we have mentioned on steps to add some character at the end of your github name when you create another instance of planet application.

**Comment by briighter** [comment]
@lmmrssa Thanks for the clarification. So if I am to visualize it Planet < Docker < Vagrant?
![image](https://user-images.githubusercontent.com/13852713/53518683-8d849c00-3a9f-11e9-9ed3-8f3e676bbea1.png)

**Comment by lmmrssa** [comment]
@briighter theoretically yes. But there are more components which make the whole system running.
Anyway this image does not relate to issue you created.
