### ISSUE TITLE
Markdown issue: Is this any Error or Bug?

### ISSUE THREAD

**Issue by Neha1990** [open-learning-exchange/open-learning-exchange.github.io#222]
Hello Team,
I want to insert Wikipedia link at the bottom of page in Vagrant.md like other links.
But it shows error in Wikipedia and left last bracket at the end of sentence.
The preview is expected but after committing, it shows different output.

my code is :
[vagrant-Wiki](https://en.wikipedia.org/wiki/Vagrant_(software))

Last bracket does not include in link and because of that expected Wikipedia link is missing.

output is different than expected See this:
https://neha1990.github.io/#!pages/vagrant.md

**Comment by DrewPerlman** [comment]
@Neha1990 I see two problems with [your code](https://github.com/Neha1990/Neha1990.github.io/blob/master/pages/vagrant.md) that are causing issues.
1. It looks like you had a merge conflict, which is why it says "HEAD" and has those "<"s and "="s: these indicate where the merge conflict is. When you push your changes, you should fix the merge conflict, then get rid of "HEAD" and all those symbols before pushing.
2. To answer your link question, apparently github.com and github.io websites have different parsers for Markdown, which is why the link acts differently on [your repo](https://github.com/Neha1990/Neha1990.github.io/blob/master/pages/vagrant.md) vs on [your github.io](https://neha1990.github.io/#!pages/vagrant.md). Check out https://blog.codinghorror.com/the-problem-with-urls/ to answer your question. I think the solution is to put `%28` and `%29` instead of the parenthesis in the link.

**Comment by Neha1990** [comment]
Hello Drew,
Thank you for reference. I read many different issues like this.
I have solve this issue.
Thanks.
