### ISSUE TITLE
Better organized step 6 and 8

### ISSUE THREAD

**Issue by lillyxxx** [open-learning-exchange/open-learning-exchange.github.io#2543]
### Problem
When explaining to interns that:
> Issues are not just about adding to the wiki, but can also involve removing repetitive or unnecessary code or content.

In Step 6 it provides a note of the above saying. And Step 8 provides an issue showing that case.

The issue and the note should be mentioned together since the issue gives examples for removing content. 

And in Step 8 we can delete the issue because the details on Github issues are all in the page `GitHub Issues`.

### Steps to reproduce the problem

N/A

### Screenshots

In Step 6:
![image](https://user-images.githubusercontent.com/33206707/61252932-21d06200-a714-11e9-81f1-a11262ab463c.png)
In Step 8:
![image](https://user-images.githubusercontent.com/33206707/61253192-f9953300-a714-11e9-9fd5-8edee080e1fc.png)

### Proposed solution

After the change, Step 6 will be:
> NOTE: Issues are not just about adding to the wiki, but can also involve removing repetitive or unnecessary code or content. (please refer to #1108)

And Step 8 will be:
> ... Through this step, you should try to further improve our Markdown Wiki, with better explanations, formatting fixes, and more! ~~(please refer to #1108)~~

**Comment by siqiuma** [comment]
This is a good catch. I just realized when I went through Step 6, I did not see the note for "less is more" maybe because it's in a blue box. However, I did clicked on the link for #1108 when I went through Step 8. My point is that at least sometimes, repetition is meaningful, especially for important concepts. For one thing, users may ignore something when they read it for the first time, just as what I did. For another, repeating important concept at multiple places in the reading helps users memorize it. I believe that's the reason that in most textbooks, key words and definitions appear multiples times throughout the chapter.
