### ISSUE TITLE
Link is not directed to accurate page.

### ISSUE THREAD

**Issue by aasenomad** [open-learning-exchange/open-learning-exchange.github.io#2614]
### Problem
I noticed that on this page (https://open-learning-exchange.github.io/#!pages/vi/vi-github-issues.md), there is a link for how to preview the change locally but I believe that it directed to the wrong page. All the information on the new page is nothing related to how to preview the change locally.

### Steps to reproduce the problem

N/A

### Screenshots

![Screenshot from 2019-08-01 23-18-47](https://user-images.githubusercontent.com/37007141/62341875-d7d8d180-b4b2-11e9-99ee-4e513c68413a.png)

and this is the directed page,

![Screenshot from 2019-08-01 23-20-02](https://user-images.githubusercontent.com/37007141/62341897-f0e18280-b4b2-11e9-9853-d2e1faf99c07.png)

### Proposed solution

I think we should direct to this link ( https://code.visualstudio.com/docs/languages/markdown#_markdown-preview ). This is what I can think of at the moment. If this is wrong or if you have a better solution, let me know. Thank

![Screenshot from 2019-08-01 23-36-09](https://user-images.githubusercontent.com/37007141/62342567-50409200-b4b5-11e9-8c68-41633a6370ac.png)

**Comment by ChiragAwale** [comment]
@aasenomad  The link you provided is for VS Code, the link that is provided in the website actually helps because it creates a server that loads the link and displays it as it will display in the website once merged. But I agree it is not that good of a tutorial so if you can find something else then please post for review. But the one you provided is not gonna work I think.
