### ISSUE TITLE
Enabling Intel VT-x on Windows 10

### ISSUE THREAD

**Issue by aaaldhaheri91** [open-learning-exchange/open-learning-exchange.github.io#291]
I enabled my Virtualization Technology a little bit differently from what it was on the link provided in step 5. Hyper-V was already uninstalled in my computer, because I couldn't find it. Below are the following steps I did to enable Intel VT-x on my Windows 10 laptop.
1. Go to **Settings**
2. Go to **Update and Security**
3. Click **Recovery**
4. Click on **restart now** button under **Advanced Startup**. 
5. Click on **Troubleshoot**.
6. Go to **Advanced Options**.
7. Go to **UEFI Firmware Settings**.
8. Click **Restart**.
9. Go down to **Virtualization Support** and click it.
10. Check the box on top where it says **Enable Intel Virtualization Technology** and click **Apply**.
11. Repeat step 10 for **VT for Direct I/O**.

**Comment by dogi** [comment]
@aaaldhaheri91 interesting
Do you wanna create a "pull request" for this?

**Comment by aaaldhaheri91** [comment]
@dogi Yes, but how is it done. Instruction page is not really clear. Do I just fork again? or just update repository through gitBash?

**Comment by cosmicvista** [comment]
i'm supposed to leave 3 comments as part of step 8, so this is one of them:

on many windows machines, upon starting up the computer you can rapidly press f2 until you boot into BIOS mode, and then disable "secure boot" option in order to use virtualization software such as virtual box. When the "secure boot" option is enabled, usually the operating system is not allowed to boot in virtual box, and this problem also applies to emulating a device for android studio to "virtual boot" into.

**Comment by waryhermit** [comment]
Which page is being discussed? Because the [link](http://www.howtogeek.com/213795/how-to-enable-intel-vt-x-in-your-computers-bios-or-uefi-firmware/) the installer script sends you to has an equivalent method, you just hold down shift while clicking restart and its the same as steps 1-4 the OP described.

**Comment by dogi** [comment]
yes that is my [link](http://www.howtogeek.com/213795/how-to-enable-intel-vt-x-in-your-computers-bios-or-uefi-firmware/) which is being discussed here

@waryhermit think we (virtual interns) are not sure where to add this information ;)

**Comment by waryhermit** [comment]
@dogi I think it would make the most sense to include the link in a note in the ole--vagrant-vi  README.md page, since that is when you are installing it and need to turn VT-x on. Then could probably remove it from the FAQ.

**Comment by dogi** [comment]
@waryhermit that reminds me we have VT-x detection abilities in the install scripts we use right now (since Nov 1)

which means I can close this ;)
