### ISSUE TITLE
Numbers do NOT match on Admin User Manual Page

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/open-learning-exchange.github.io#2923]
### Problem  

On the Admin User Manual page, under section **How do I upload a Resources?**. The numbers marked in the screenshot provided do not match the instructions below. Also, there are repeated numbers and some numbers marked in the screenshot do not get illustrated in the detailed instruction below.

### Steps to reproduce the problem  

Go to **Tech Geniuses**, select **Admin User Manual**, and choose **How do I upload a Resouces?** on the navbar at the left side, and scroll down to see.

### Screenshots
<img width="1452" alt="Screen Shot 2020-04-14 at 9 51 17 PM" src="https://user-images.githubusercontent.com/57075986/79290854-28565a80-7e9b-11ea-908a-725125a286b3.png">
<img width="1463" alt="Screen Shot 2020-04-14 at 9 39 42 PM" src="https://user-images.githubusercontent.com/57075986/79290862-2c827800-7e9b-11ea-854a-a5f2a215cd64.png">
<img width="1492" alt="Screen Shot 2020-04-14 at 9 40 29 PM" src="https://user-images.githubusercontent.com/57075986/79290866-31dfc280-7e9b-11ea-842e-33e34d7cdf05.png">
<img width="1460" alt="Screen Shot 2020-04-14 at 9 40 59 PM" src="https://user-images.githubusercontent.com/57075986/79290895-44f29280-7e9b-11ea-998a-8ff98d6c0f3c.png">

### Proposed solution  

Change the introduction part to match the screenshot or use another screenshot.

**Comment by chtelmko** [comment]
They might have used a screenshot from an earlier version. I still found the screenshot useful.

**Comment by mdwattendorf** [comment]
All of these topics are identical to the topics in the "Content & Manage Library" section:
https://open-learning-exchange.github.io/#!pages/techgenius/tg-library-management.md

Those screenshots are out of date too, but I've created issues for them: #2926 and #2927

Maybe we can change these four sections to just one (e.g. "Content & Library Management") and link to the page dedicated to those topics to remove the redundancy.  Otherwise every time the UI is updated, the screenshots and directions will have to be updated in two places.  Bonus would be it will shorted the admin user manual page so users won't have to scroll as much to find information.

**Comment by Haoran-Hu** [comment]
@mdwattendorf  What you proposed definitely makes sense since these are identical topics. Maybe they are included twice to make the Admin User Manual more comprehensive and complete. Great suggestion anyway.

**Comment by lmmrssa** [comment]
@Haoran-Hu you can work on fixing numbering. 
Regarding **Admin Manual** and **Library management** **Library management** still has old content. And it was focused mainly to help create content where as admin manual was for whole system management.

**Comment by Haoran-Hu** [comment]
@lmmrssa Thank you for your feedbacks. I was thinking about the same thing as the Admin User Manual should be as comprehensive and complete as possible.
