### ISSUE TITLE
Step 2 is kind of unclear

### ISSUE THREAD

**Issue by meharshahani** [open-learning-exchange/open-learning-exchange.github.io#2924]
### Screenshots
N/A 

### Proposed solution
Also since everyone is going past Step 1 and is creating a community on planet before moving to step 2, we can remove the warning section where it is said not to run the "docker-compose -f planet.yml -p planet up -d". This will make the section precise and less confusing.

**Comment by chtelmko** [comment]
If you are talking about this warning :

"WARNING: If you followed Step1 and configured Planet, you should not run docker-compose -f planet.yml -p planet up -d. It might destroy your configuration. vagrant up prod runs docker-compose -f planet.yml -p planet up -d automatically. If you are in this situation, look at the Second and third element of Troubleshooting in this page"

I think its a valid one, because we don't want someone to accidently destroying their working machines(and having to start all over).

I do agree that maybe rewarding that, might help. Maybe just saying that  vagrant up prod runs docker-compose -f planet.yml -p planet up -d automatically.

**Comment by meharshahani** [comment]
Yep agree with you. Thanks for the feedback
