### ISSUE TITLE
 Formatting and inactive links in htmlresources.md

### ISSUE THREAD

**Issue by favour-nerrise** [open-learning-exchange/open-learning-exchange.github.io#294]
1. All links under the 5 sections, **"Objective"**, **"Documentation"**, **"Porting HTML App to CouchApp"**, **"CouchApp Installation"**, **"Adding the app as resource to Bell App Library"**, should open up in a new tab.
2. Links to **"Couchapp"** and **"Couchdb Instance"** under **"Prerequisites:"** are currently inactive.

**Comment by aberdean** [comment]
Point 1 is probably better addressed simply by Right Click -> Open Link in New Tab, rather than mixing up HTML and Markdown.

Point 2 is a really good point that needs to be addressed!

**Comment by hikaruit15** [comment]
@aberdean Could we add more code in index.html to open an external link in new tab?
```javascript
$(document).ready(function() { 
    $( "body" ).on( "click", "a", function() {
        $("a[href^='http://']").each(
        function(){
            if(this.href.indexOf(location.hostname) == -1) {
                $(this).attr('target', '_blank');
            }
    });
         
    $("a[href^='https://']").each(
        function(){
            if(this.href.indexOf(location.hostname) == -1) {
                $(this).attr('target', '_blank');
            }
    });
});
 });
```
I tried it with [my site](https://hikaruit15.github.io/#!index.md). It works well!

**Comment by aberdean** [comment]
@hikaruit15 I like your code very much, but I'm not sure if it's a good idea to add a lot of modifications to index.html, because of the reason we spoke about earlier (i.e. gets overwritten at each update, so we need to add instructions to fix it every time we update). 
I'm not totally against it either, though.
@dogi, what do you think?

**Comment by dogi** [comment]
@aberdean I totally understand your hesitation here

but since `index.html` got already changed twice in the past
it is not such a big problem anymore


@hikaruit15 clicking around on your .io page I found out that there are some additional fixes which need to be done - absolute URLs of type open-learning-exchange.github.io need also to be changed in relative ones

**Comment by hikaruit15** [comment]
I just added instructions to README.md and fix links.
