### ISSUE TITLE
Missing information on Planet Quick Start Manual page

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/open-learning-exchange.github.io#2955]
### Problem
On **Planet Quick Start Manual** page, under section **Basic Troubleshooting**, for the last point, there should be a screenshot as it was stated; however, the screenshot is missing.

### Steps to reproduce the problem  
Go to **Tech Geniuses**, then select **Quick Start Setup**, scroll down to the bottom of the page to see.

### Screenshots
![Screen Shot 2020-04-17 at 6 06 57 PM](https://user-images.githubusercontent.com/57075986/79618535-48269200-80d8-11ea-96ff-b89cd3ee8973.png)
![Screen Shot 2020-04-17 at 6 07 13 PM](https://user-images.githubusercontent.com/57075986/79618538-4bba1900-80d8-11ea-8f77-831e9a78aa6e.png)

### Proposed solution
Either add a screenshot to match the description or change the wording of the sentence.

**Comment by lmmrssa** [comment]
@Haoran-Hu our system does not require internet to use. And based on the content and NOTE below it seems like it is pointing to connection between (laptop/tablet) and raspberrypi. 
Also to know if it is connected or not you will have to open url on browser that is related to rpi. So you need to specify that as well. So update content to specify url to check and also update picture so that picture reflect url itself.

**Comment by Haoran-Hu** [comment]
@lmmrssa Thank you for your feedback! I will be working on that.
