### ISSUE TITLE
MDwiki Docs bad link

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/open-learning-exchange.github.io#2970]
**Problem:**
The [www.notesync.org]: http://www.notesync.org/  link At the bottom of the page is not working.

**Steps to reproduce the problem:**
Going to [FAQ page in MDwiki](http://dynalon.github.io/mdwiki/#!faq.md)

**Screenshots:**

![noteSynk link](https://user-images.githubusercontent.com/40531136/80121928-dbd5e380-855a-11ea-9cd5-3a81e82e601b.png)

![noteSync error](https://user-images.githubusercontent.com/40531136/80121940-e1cbc480-855a-11ea-9a70-bb715aa352df.png)

**proposed solution:**

Change the link to say [www.notesync.com]: http://www.notesync.com/ ?

**Comment by jsschf** [comment]
I'm not sure if it's a huge deal but the webpage has valid security certificates, like if you manually put "https" at the beginning of the domain rather than "http". So my suggestion would be to in addition to fixing the broken link, have the link include "https" rather than "http". Good catch though, I've been checking all the links as well for small issues like that.

**Comment by lmmrssa** [comment]
http://dynalon.github.io/mdwiki/#!faq.md is not our page so we can not control it
