### ISSUE TITLE
Add vagrant instructions for Fedora

### ISSUE THREAD

**Issue by sncarlson** [open-learning-exchange/open-learning-exchange.github.io#3048]
### Problem
While this wasn't exceptionally complex, there were some extra steps needed to get Fedora, Planet, virtualbox, and vagrant cooperating.  To have a basic set of steps available would have been convenient. 

### Steps to reproduce the problem

Navigate to: https://open-learning-exchange.github.io/#!./pages/vi/vi-planet-installation-vagrant.md.  Notice absence of Fedora instructions.

### Screenshots

![Screenshot from 2020-05-16 08-26-37](https://user-images.githubusercontent.com/843208/82120571-2bbc5a80-9755-11ea-9674-7d8a4ba57b31.png)

### Proposed solution

Add similar instructions based on Ubuntu example.

**Comment by anthonyhvo12** [comment]
@sncarlson I agree. Some of the steps also apprear to be out of date. Like under the **For Ubuntu** section, it is technically not correct to copy the 64-bit download link since it will install the newest version of Vagrant, not the recommended versions below 2.2.5 as pointed out earlier on the page. 
![Screen Shot 2020-05-16 at 10 39 55 AM](https://user-images.githubusercontent.com/43098273/82122435-b1de9e00-9761-11ea-9a18-4f15e3b808d0.png)

**Comment by sncarlson** [comment]
Will close and open new issue with more appropriate to suggestion made in fix.
