### ISSUE TITLE
Step 8 steps could be clarified using bullets, font, and headers

### ISSUE THREAD

**Issue by rheam97** [open-learning-exchange/open-learning-exchange.github.io#3154]
### Problem
I think that the bottom of step 8 is fairly straightforward, but the top is a large block of text like the rest of the steps. It can be a lot, so i figure there can be bullet points or numbered steps where it talks about creating issues and waiting for them to be approved, etc.

### Screenshots

<img width="759" alt="Screen Shot 2022-02-28 at 2 02 17 PM" src="https://user-images.githubusercontent.com/94139372/156043290-2dcfc01f-4f01-4c03-b2e6-ed143a899168.png">

### Proposed solution

adding bulleted points and separating tasks from objective and purpose using headers.

**Comment by lmmrssa** [comment]
@rheam97 purpose of these steps is not to complete it too fast. But to understand the whole workflow, standards and guideline. that's why we have lot of linked content to help understand all in detail. If you can make it short still being able to explain the points. then please feel free to improve it. We will look into it and if it looks good then will merge it.

**Comment by rheam97** [comment]
i will just break it up more and make it more clear with different formatting. I think that the last part that you're referring to @lmmrssa makes sense but it could be more clear in the first half of the page
