### ISSUE TITLE
Step 8 Issue I: Each step has long paragraphs instead of key bullet points for key information

### ISSUE THREAD

**Issue by axzhir** [open-learning-exchange/open-learning-exchange.github.io#3225]
### Problem

Each step associated with the website has long paragraphs explaining the steps and even recommendations. Usually, there are around 4-5 sentences per paragraph. Sometimes a little more, sometimes a little less.

### Steps to reproduce the problem

N/A

### Screenshots

<img width="609" alt="Screenshot 2024-05-09 at 19 31 01" src="https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/122408118/4eefddeb-db59-47a9-abe5-f46e68d3dd6e">

### Proposed solution

I believe that for recommendations/suggestions, they can be written in a box as notes. Like how notes are generally written on the website. As for the paragraphs that talk about the steps, I believe that putting those steps as bulletpoints or an a/b/c list would help a lot with this.

**Comment by xyb994** [comment]
Good point, step 8 is for sure cluttered and need some cleanup.

Please remember each issue should be clear and focus on a specific problem or improvement. Since your screenshot is about item 6 in step 8, I suggest you focus on that part. Please use this issue to convert "Step 8 - 6. Create a Pull Request" with appropriate bullet points/lists and `Note:`
