### ISSUE TITLE
Step 8 - Instructions for Create a New Branch needs more examples

### ISSUE THREAD

**Issue by strawberrybread** [open-learning-exchange/open-learning-exchange.github.io#3274]
### Problem
Under Step 6 part 4, the instructions for creating a new branch just shows the same screenshot from step 1 for creating a profile. This does not give enough information for how to choose an appropriate branch name.

### Steps to reproduce the problem
N/A

### Screenshots
![image](https://github.com/open-learning-exchange/open-learning-exchange.github.io/assets/112584985/35deb71f-9dfe-49b9-8342-018722b88530)

### Proposed solution
Add more branch name examples and specify that a descriptive name for the issue should be used for the branch.
Can move Step 7 before Step 6 so that vi can take the Github course first before reaching Step 6.

**Comment by xyb994** [comment]
A ctually the bottom half of the screenshot content is due to be removed, there's another Pull request for it but it's been inactive for 9 days. It's confusing to show how to create a branch on GitHub web interface but mentioning how to create a branch in command line right after. What we want is the latter on for this step.

Regarding
