### ISSUE TITLE
Add Detailed Timeline to the First Steps Guide

### ISSUE THREAD

**Issue by RicaRodz** [open-learning-exchange/open-learning-exchange.github.io#3388]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md

### Problem

The current First Steps guide lacks a detailed timeline or suggested pacing, which could benefit those balancing other commitments. While it mentions that most candidates finish the steps in 7-8 days, it would be helpful to provide approximate time needed for each step.

### Proposed solution(s)

Add a section at the beginning of the guide that offers a suggested timeline, breaking down each step with an approximate time needed to complete

**Comment by xyb994** [comment]
Do you plan to use a list or table for this? What is your time estimate for each step? Would it be better to add the time estimates to each step's specific page (if applicable)?

I feel it might be difficult to estimate, and the Git/GitHub section could vary depending on experience.

**Comment by RheuX** [comment]
I think it's better to add time estimates based on each steps. You can always overestimate the steps for a bit (like assuming they don't have docker installed, or git installed; basically assume they starting from 0).

I feel like giving estimates time is better so that everyone can know how many times they should prepare for each steps, and can plan their plan accordingly. So maybe they can sneak some steps in during the day.

I think the instruction are clear enough where it doesn't make people with more experience finish it faster also.

**Comment by RicaRodz** [comment]
I was considering adding an initial "Suggested Timeline & Tips" section that provides a rough overview, with estimated time ranges based on experience levels.

For example:

Step 2: Software Prerequisites
Estimated Time: 2-3 hours
Setting up the development environment may take longer depending on how familiar you are with the tools.

These estimates are intended as a rough idea of the minimum time required for each step. I feel this could help prospective interns manage their time better.

**Comment by xyb994** [comment]
I’m inclined to suggest adding those to vi-first-steps.md under each step’s section, as most are already summaries of the respective steps. However, we should ensure they remain brief and concise. But if people move on between steps without going back to vi-first-steps.md might miss the information.

**Comment by Gavinp14** [comment]
I like the idea of adding an estimated time section to each step. For me since I already had docker and git installed that step did not take me as long as someone who does not have them installed. I also think in the overview page we should have a table called time estimates with two columns. One column is the steps, and the other is the estimated time. 

It would like something like this...

steps | est. time to complete
--------------------------------
step 1 | 2-3 hrs
--------------------------------
step 2 | 1-2 hrs

https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md right under the FAQ section, I think it would fit nicely.

**Comment by jessewashburn** [comment]
Absolutely agree. Having a time estimates for the steps and the process overall would have helped me manage time over the 7-8 days. A table is a smart way to organize this.

**Comment by xyb994** [comment]
@RicaRodz Can you provide your time estimation [in this google sheet](https://docs.google.com/spreadsheets/d/1SuaiOyYFoXPSEoxw1jD-XpVIWTTKoEr5TbU0rfrkk10/edit?usp=sharing)?
