### ISSUE TITLE
confusing section (courses - action list page) on the planet user manual

### ISSUE THREAD

**Issue by RheuX** [open-learning-exchange/open-learning-exchange.github.io#3401]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!./pages/manual/planet/course.md

### Problem

In the planet manual - Course section, I found that the `Action on List Page` is very confusing to follow, especially with little subheading or bullet point; with a lot of numbering point.

### Screenshots (when necessary)

<img width="725" alt="Screenshot 2024-10-10 at 10 13 40 PM" src="https://github.com/user-attachments/assets/ba332e7f-aea9-44b3-924d-6605519974a8">

### Proposed solution(s)

I want to change the format of this section specifically into something like below:

- **Adding a Course**  
  To add a course, press the "+" button.

- **Joining a Course**  
  Select the checkbox next to a course, then click the **"Join Selected"** button.
  - The selected course will now be part of your **myCourses**, and visible on the front page dashboard.
  - You can join multiple courses at once.
  
  Alternatively:
  - Click on a course in the list, then click the **"Join"** button near the top-right of the course page.

- **Leaving a Course**  
  Select the checkbox next to a course you're already part of, then click the **"Leave Selected"** button.
  - The course will be removed from **myCourses** and no longer appear on the front page dashboard.
  - You can leave multiple courses at once.

-------------------- the rest of the information ------------------  (we can also add photos as necessary)

With this format, users/readers will be able to know instantly what action they can do, and locate the want they want to do with the necessary steps/information.

Please let me know what you guys think :)

**Comment by jessewashburn** [comment]
Nice! I like your formatting a lot better.

Another problem that the text could address that the plus sign actually creates a brand new course, rather than allowing the user to join an existing one (i.e _add_ it to their library), which is ambiguous. Maybe it should say: 

**Creating** a **new** Course
To create a **new** course, press the "+" button.

Joining an **existing** Course
Select the checkbox next to a course, then click the "Join Selected" button.

    The selected course will now be part of your myCourses, and visible on the front page dashboard.
    You can join multiple courses at once.


The other issue is that in myDashboard the "Add item to myLibrary" button goes away once there is a single item added to that section. Adding items should be a separate button here, but in the meantime, this text could mention that the user should go to the Library Tab to join more courses, which will then appear in the dashboard. 

Again, the use of add and join is used somewhat interchangeably, which I think will be a source of confusion for some.
