### ISSUE TITLE
Missing: myDashboard section under Feature of Planet

### ISSUE THREAD

**Issue by jessewashburn** [open-learning-exchange/open-learning-exchange.github.io#3407]
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md

### Problem

There is no section explaining the myDashboard page, which would be helpful, as it is one of the most complex pages on the app. There appear to be some issues with this page in the app itself, so perhaps a full explanation of every feature should come after they are fixed. 
I am happy to provide further feedback on these issues, although it's somewhat out of the scope of this assignment. 

### Proposed solution(s)

For now, a placeholder section like was done with Tests is recommended, i.e:

## mYDashboard

**This portion needs to be worked on**

**Comment by Gavinp14** [comment]
I agree, after checking this out I also think that this section...

Nations

Nations always exist in the cloud and require an internet connection to access.
Each Nation serves as a central repository for the Community or a group of communities that it serves.
Different Nations cannot connect to each other.

Communities

A Community is a local installation of the Planet system.
A Community does not require an internet to access.
Users can connect to a Community using any device having a web browser like tablet, computer, etc. The connection is established via a router through a locally configured intranet.
Each Community connects periodically to a Nation via internet in order to receive new materials and to upload user metrics.
A Community is not able to connect to other Communities.

could be explained a bit more simply in my opinion

**Comment by RheuX** [comment]
> I agree, after checking this out I also think that this section...
> 
> Nations
> 
> Nations always exist in the cloud and require an internet connection to access. Each Nation serves as a central repository for the Community or a group of communities that it serves. Different Nations cannot connect to each other.
> 
> Communities
> 
> A Community is a local installation of the Planet system. A Community does not require an internet to access. Users can connect to a Community using any device having a web browser like tablet, computer, etc. The connection is established via a router through a locally configured intranet. Each Community connects periodically to a Nation via internet in order to receive new materials and to upload user metrics. A Community is not able to connect to other Communities.
> 
> could be explained a bit more simply in my opinion

How would you propose it to be explained, I feel like it's pretty simple to me to understand, especially with the relevant pictures.
