### ISSUE TITLE
GitHub Issues page should teach you to create a branch for each pull request.

### ISSUE THREAD

**Issue by waryhermit** [open-learning-exchange/open-learning-exchange.github.io#360]
You cannot submit multiple **separate** changes unless you create branches for each of your changes. The GitHub issues page should at least mention this, or teach you how to.

**Comment by dogi** [comment]
@waryhermit like that - please make a suggestion how to integrate this with our steps

**Comment by waryhermit** [comment]
@dogi I have modified my copy of the GitHub Issues page (githubissues.md), check out out and tell me if this is a good way to integrate it into the steps. If it is I can start a pull request, otherwise tell me what could be improved.

**Comment by aberdean** [comment]
@waryhermit The modification you made is awesome! 
The only thing I'd change is using `git status`, `git add .` (or `git add [filenames]`, depending on the situation), and `git commit -m "commit message"` instead of using `git commit -a`.
The reason being that it gives you more opportunities to catch possible errors before committing your changes.
