### ISSUE TITLE
Adding Help/FAQ  tab to Markdown Wiki

### ISSUE THREAD

**Issue by vimalababu4** [open-learning-exchange/open-learning-exchange.github.io#37]
Why can't we add one more tab  to the Markdown Wiki: http://open-learning-exchange.github.io/ll_CC/#!index.md ,   that would be Help/FAQ that may be an assembled list of many questions and their answers that will help the new virtual interns or users when these questions tend to occur.  For example: if i ask questions and  get answers from you, i can post them in help/faq section that might help others who have similar questions

**Comment by dogi** [comment]
Really like this suggestion:

- [ ] lets everybody brainstorm here in the comments about possible questions
- [ ] also try already answer the raised questions

**Comment by dogi** [comment]
@vimalababu4 suggested in https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/44 following:

What do these 3 tools mean ? Git, Virtual Box and Vagrant?

Git (/ɡɪt/) is a version control system that is widely used for software development and other version control tasks. Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency. Git is easy to learn and has a tiny footprint with lightning fast performance. It is a distributed revision control system with an emphasis on speed, data integrity, and support for distributed, non-linear workflows. For more info https://git-scm.com/documentation

Virtual machine manager is like virtualbox. VirtualBox is a cross-platform virtualization application. What does that mean? For one thing, it installs on your existing Intel or AMD-based computers, whether they are running Windows, Mac, Linux or Solaris operating systems. Secondly, it extends the capabilities of your existing computer so that it can run multiple operating systems (inside multiple virtual machines) at the same time. For more info https://www.virtualbox.org/wiki/Documentation

Vagrant is a script for manipulating virtualbox and is the command line utility for managing the lifecycle of virtual machines For more info https://www.vagrantup.com/docs/

**Comment by dogi** [comment]
please add more

**Comment by dogi** [comment]
@fsjoyti  in https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/59 suggested:

We could do a separate tab for answering frequently asked questions such as merge conflicts or not being able to do a pull from the github remote repository. It could be part of the faq tab in markdown wiki or a separate tab altogether
