### ISSUE TITLE
faq.md change 15 hours to 16 

### ISSUE THREAD

**Issue by hannahgdubin** [open-learning-exchange/open-learning-exchange.github.io#383]
I noticed that it said on the page that this internship requires 15 hours of work however, dogi said that it has a minimum requirement of 16 hours. The indeed job posting also says 16 hours.

**Comment by IshanSoni** [comment]
@hannahgdubin you can also put 15-16 hours.

**Comment by aberdean** [comment]
@hannahgdubin @dogi confirmed it's 16 hours, so you're welcome to submit a PR.

**Comment by hannahgdubin** [comment]
@aberdean  https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/385 I believe I already created the PR... unless it won't work properly because I am resubmitting my personal page. If it won't work I will create a new one. Thanks!

**Comment by aberdean** [comment]
@hannahgdubin it's not a matter of working or not working (I can modify your PRs, so they can always "work").

The problem is that you need to learn how to keep your fork updated and submit clean pull requests, before you can join the interns team (since, when you join, you'll have to do plenty of pull requests).

Please, follow the instructions I gave you yesterday and submit a clean pull request.

**Comment by hannahgdubin** [comment]
Will do. Sorry for any confusion!
