### ISSUE TITLE
Instructions to launch vagrant should not be exclusive to mac and ubuntu in bell-apps tutorial

### ISSUE THREAD

**Issue by IshanSoni** [open-learning-exchange/open-learning-exchange.github.io#403]
In the bell-apps tutorial, it says 
>Please, check that your vagrant is up and running with vagrant global-status. Assuming that it's running or you launch it using vagrant up

only for Mac and Ubuntu instructions. However, every time I have to launch my community in windows I have to use vagrant up beforehand otherwise it does not work. I was very lost at this process because I was not able to make it work due to the commands being only in the mac and ubuntu portion.

**Comment by IshanSoni** [comment]
I suggest putting this part 
>Please, check that your vagrant is up and running with vagrant global-status. Assuming that it's running or you launch it using vagrant up

in the introduction paragraph of the page. And also cd to ole--vagrant-vi before running those commands otherwise it gives an error

**Comment by aberdean** [comment]
@IshanSoni For Windows users, we have two scripts, both of which will automatically start your community.
If one of the scripts doesn't work properly, you should have just reported it in chat and we would have asked you which script you used and helped you troubleshoot the issue.

There is no need for Windows users to use `vagrant up`, that's why it is not included in the Windows Vagrant tutorial.
