### ISSUE TITLE
Markdown suggestion

### ISSUE THREAD

**Issue by marty135** [open-learning-exchange/open-learning-exchange.github.io#473]
Adding installation methods for Arch, Debian and Fedora.

![screenshot from 2017-02-01 10-08-42](https://cloud.githubusercontent.com/assets/8263847/22468155/127c100a-e813-11e6-9a49-4b997c834551.png)

**Comment by waryhermit** [comment]
@marty135 I am not vary familiar with various Linux distros. Could you explain more why the Ubuntu directions wouldn't work with those distros?

**Comment by dogi** [comment]
@waryhermit because they use other package managers ... and packages do not only have other names but also other dependencies ;)

@marty135 question is more since of more then 100 virtual intern attempts there was only 4 with Linux as OS and all of them was running Ubuntu ... do we want Arch and Fedora install explicit written out.
Debian should kinda already work out of the box ...

**Comment by waryhermit** [comment]
@dogi OK, but if they are nerdy enough to use something other than the Ubuntu wouldn't they know how to kinda translate Ubuntu commands to the versions that would work on their setup? I mean I kind of agree with what you are saying, its not likely that we will have many (if any) that use those distros, and if we do get them they can write the directions right? 😛

**Comment by dogi** [comment]
bingo @waryhermit - I am also believing that the chance this people would know how to adopt this ubuntu scripts to their Distro is high ;)

this is how many distros we could try to support http://futurist.se/gldt/wp-content/uploads/12.10/gldt1210.svg

**Comment by marty135** [comment]
@dogi I see what you mean, closing the issue for now.
