### ISSUE TITLE
[SUPER EASY] Update member join/leave dates

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/open-learning-exchange.github.io#503]
As you can see in http://open-learning-exchange.github.io/#!pages/team.md

there many missing `Join Date` s

Action:
- track down first commit from a intern without join date and save that link for later
- create a branch whrere fill out the missing table spot (date format is YYYYMMDD)
- create a pull request where you add this link of prove in description, title is `archeology success with <username>`

**Comment by sarvanivadali** [comment]
Hi @dogi One pull request for all missing dates?

**Comment by sarvanivadali** [comment]
Solution is to use the following command to get first commit ever made by an author (assuming if squashing a commit will not alter commit history).

```git log -1  --oneline --reverse --pretty=format:"%an%x09%ad" --author='dogi'```

**Comment by sarvanivadali** [comment]
There seems to be a known issue with ```-1``` and ```--reverse```. So instead suggested command is:

```git log --pretty=oneline --reverse --pretty=format:"%an%x09%ad" | head -1```

**Comment by dogi** [comment]
@sarvanivadali @dogi here is really curious about the output ;) Could drop a copy of it in the chat?

**Comment by sarvanivadali** [comment]
@dogi sample output for author ```dogi```:

![image](https://cloud.githubusercontent.com/assets/8753852/23144122/8b0b9bf0-f793-11e6-8b43-e1f458c04ca7.png)

**Comment by waryhermit** [comment]
I think I missed something - the pull request was merged and the issue close, and then reopened. Were only some of the join dates fixed?

**Comment by waryhermit** [comment]
To be clear to anyone else reading, yes, there are more join/leave days to be added.

**Comment by sarvanivadali** [comment]
Hi @waryhermit I used first commit time as a basis to determine join dates for all interns (i.e pages/<username>.md file commit history). I was not able to determine start dates for these three users (AdityaNair99, epistulae and i5o) - Because, i5o created them all at the same time. Also, I couldn't figure out how to determine their last dates. I need to fork/clone all the projects in OLE and look for final commit dates a particular author made and get latest date. Which is doable (if that hypothesis is accurate).

### Proposal to determine last dates:
Fork/clone all repositories under <https://github.com/open-learning-exchange> and use history of a specific author in reverse chronological order using above mentioned git command.

**Comment by waryhermit** [comment]
The dates for the last two are:

**epistulae**
Join: Jun 1, 2016
Leave: July 2016

**Neha1990**
Join: Jul 12, 2016 
Leave: Sep 26, 2016

**Comment by mappuji** [comment]
solved by #788
