### ISSUE TITLE
extra words in firststeps.md

### ISSUE THREAD

**Issue by Supriyaranjan** [open-learning-exchange/open-learning-exchange.github.io#576]
Similar to issue https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/555
I noticed there are too many extra words like "please" in firststeps.md. Will it be better if these extra words are removed?

**Comment by blazerchamp** [comment]
I had a VM problem when trying to access MyBell. The solution given to me was to install a vagrant git repository which contained files that eventually solved the VM problem that prevented me from accessing MyBell. The instructions and links for this suggestions need to be added so that applicants don't have to wait on any team member to provide them with the git repository. Instead, they will download it and simply follow the instructions to install the repository, and 'vagrant up' their machine to get access to MyBell.

**Comment by waryhermit** [comment]
@blazerchamp

1. How does that relate to this issue?
2. That solution is not needed most of the time, as most people do not have a corrupted vm.
3. The directions to fix a corrupt vm are already in the [FAQ](http://open-learning-exchange.github.io/#!pages/faq.md)

Also this issue was already solved so I am closing it.
