### ISSUE TITLE
Team Member missing from Team page

### ISSUE THREAD

**Issue by pranesh-s** [open-learning-exchange/open-learning-exchange.github.io#62]
Although pranesh-s.md is a part of the repository, it needs to be added to the team member page. This can be done by editing in the line:

    [pranesh-s](/ll_CC/#!pages/pranesh-s.md)

in the team.md file. In addition, there are also team members on the page without a .md file attached. They are the following:

    [mhalqurashi](/ll_CC/#!pages/mhalqurashi.md)
    [ptruong88](/ll_CC/#!pages/ptruong88.md)
    [xbxme12345](/ll_CC/#!pages/xbxme12345.md)
    [sdronika](/ll_CC/#!pages/sdronika.md)
    [mduprez](/ll_CC/#!pages/mduprez.md)
    [shorabhd](/ll_CC/#!pages/shorabhd.md)
    [SavinSachdev](/ll_CC/#!pages/SavinSachdev.md)

I am not sure what kind of change needs to be made regarding these team members. Finally, one team member links to the wrong .md file.

    [alan459](/ll_CC/#!pages/alan459.md) -> should be [alan459](/ll_CC/#!pages/Alan259.md).

I have made changes fixing the first and last issue and have sent a pull request.

**Comment by dogi** [comment]
@pranesh-s suggested https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/63/files

**Comment by dogi** [comment]
I will accept this pull request, because it fixes 2 problems

* no link to @pranesh-s 
* wrong linking to @alan459 - which since the unspoken agreement that userfile should be the same way as the github username, is not the error - the filename written in capital letter is that thing what needs to be changed

@alan459 or somebody else please fix that - https://help.github.com/articles/renaming-a-file/

anyway better then before that is why pull request gets accepted

for the missing links please somebody go for it

**Comment by dogi** [comment]
too late @EmilyLarkin did most already - https://github.com/open-learning-exchange/open-learning-exchange.github.io/commit/4212517958767272d84fd5150e7692f7c965794a

**Comment by dogi** [comment]
The only think left is the link of @alan459 which is a very simple fix

**Comment by AdityaNair99** [comment]
Just submitted a pull request that changed the file name and the link #122
