### ISSUE TITLE
Improve the registration part in "Step 4 - BeLL-Apps Tutorial"

### ISSUE THREAD

**Issue by tianhaopx** [open-learning-exchange/open-learning-exchange.github.io#631]
According to the tutorial, after we register in our local community BeLL app, the admin should accept the request in nation side. However, I waited one day and didn't get accepted. In step 7, I found I can actually log in to nation side and accept the request by myself. So I think we should add a note in step 4.

**Comment by waryhermit** [comment]
@dogi .. You were saying someone would figure out how to do that soon haha

**Comment by dogi** [comment]
@waryhermit ;)

@tianhaopx you was not supposed to do that ... no worries

just wanted to say that I check at least every 24 hours for new communities
so you must have been very unlucky - specially since in 3 days I accepted at least 6 communities ;)

since you accepted your own community you was not getting a publication from me and because of that not able to finish step7 ...

**Comment by dogi** [comment]
@waryhermit think we need to start using VIPlinks ...

**Comment by tianhaopx** [comment]
@dogi since I am not supposed to do that, so these two issues #631 #632 should be closed?

**Comment by dogi** [comment]
@tianhaopx yes and no ;)

I already closed the other issue, but we will use this one to promote VIPlinks instead of login as supermanager into the nation ...

this fix will disable aspiring virtual interns to mess up the normal *slow* workflow ;)

**Comment by waryhermit** [comment]
https://github.com/ole-vi/BeLL-Apps/issues/99
