### ISSUE TITLE
layout in crowdinintegration.md page

### ISSUE THREAD

**Issue by yssdnj** [open-learning-exchange/open-learning-exchange.github.io#684]
how do you guys think about this page [crowdin integration](http://open-learning-exchange.github.io/#!pages/crowdinintegration.md). Does it need to reformat?
Like,  images size, format of content.

**Comment by mappuji** [comment]
Hi @yssdnj thank you for your issue.

But, it is considered as best practice if your issue contains a suggestion, a problem, or proposal. However, thank you for remind us about crowding page. You can improve the page by removing whitespace in some image on that page, so that people can see the image more clearly. You can raise your PR if you're done and refer to this issue.

**Comment by yssdnj** [comment]
@mappuji Yes, I would like to try my best to optimize it.

**Comment by waryhermit** [comment]
@yssdnj Hey, any progress on a pull request?

**Comment by Loshma93** [comment]
@yssdnj Are you working on this issue. If you are not working on this I can reformat crowdinintegration.md page. Please let me know.

**Comment by yssdnj** [comment]
@Loshma93, please reformat it. I have no good ideas about it.

**Comment by Loshma93** [comment]
@yssdnj Ok. I will work on it.

**Comment by waryhermit** [comment]
Fixed by #747 I think
