### ISSUE TITLE
Incorrect headers on nation.md and one instruction looks out of place

### ISSUE THREAD

**Issue by snazzybunny** [open-learning-exchange/open-learning-exchange.github.io#770]
The headers on nation.md are not according to markdown syntax. The # sign and accompanying text should have a space between them. They do not render correctly on github. Thoughts?

Update by @mappuji
To-fix:
- [ ] bellapps.md *(Each header is incorrectly formatted)*
- [x] chat.md *(This page is more rough than anything, some issues with unfinished quotes, although no substantial header issues)*
- [ ] planetusermanual.md *(The "How do I navigate the dashboard" header is incorrectly formatted)*
- [ ] takehome.md *(The first 2 headers both require spaces before the text)*
- [x] vagrant.md *(The final header, returning the user to the first steps page is incorrectly formatted)*

**Comment by snazzybunny** [comment]
Also, instructions on line 26 look out of place probably to emphasize username and password. Perhaps we can put some things in bold? Right now it looks awkward.

**Comment by aurinsomnia** [comment]
I think it would be greatly beneficial if you could post a screenshot of what you're seeing, because it can be hard to notice these things at a glance. It would make understanding the issue a lot easier and less abstract.

**Comment by mappuji** [comment]
Hi @snazzybunny and @aurinsomnia yes, some header is not properly formatted. It looks okay in MDWiki, but not in the GitHub Markdown preview. It is due to lack of space after the last hashtag of the header.

For example:
`### Header 3`
but written as
`###Header3`

I think it would be better if we have a consistent formatting and it would be great if there is any aspiring intern want to look through each `md` file and spot for an improper header. Because it is occurs in many pages.

Either @snazzybunny and @aurinsomnia you can create a list of items of some pages with improper header formatting, and lets other aspiring interns solve it one-by-one.

Example:

- [ ] Page 1
- [ ] Page 2
- [ ] Etc

Please create the list with a comment on this issue, and some moderators will move the result on the issue description as an update.

**Comment by aurinsomnia** [comment]
Hi @mappuji,
 I have gone through each individual page on the ole github.io and checked for formatting issues as you requested. There aren't an overwhelming amount of issues, but of the 22 pages I looked through 5 had some header formatting issues. 
The pages in question are:
- bellapps.md *(Each header is incorrectly formatted)*
- chat.md *(This page is more rough than anything, some issues with unfinished quotes, although no substantial header issues)*
- planetusermanual.md *(The "How do I navigate the dashboard" header is incorrectly formatted)*
- takehome.md *(The first 2 headers both require spaces before the text)*
- vagrant.md *(The final header, returning the user to the first steps page is incorrectly formatted)*

**Comment by mappuji** [comment]
Thank you @aurinsomnia 😄 
I will create a list for to-fix:
- [ ] bellapps.md *(Each header is incorrectly formatted)*
- [ ] chat.md *(This page is more rough than anything, some issues with unfinished quotes, although no substantial header issues)*
- [ ] planetusermanual.md *(The "How do I navigate the dashboard" header is incorrectly formatted)*
- [ ] takehome.md *(The first 2 headers both require spaces before the text)*
- [ ] vagrant.md *(The final header, returning the user to the first steps page is incorrectly formatted)*

**Comment by snazzybunny** [comment]
I believe vagrant.md is solved. Chat.md has no header errors but may need refining. The other 3 files are referenced in the pull requests by @aurinsomnia.

**Comment by waryhermit** [comment]
@mappuji I checked all the files, they all seem fixed
