### ISSUE TITLE
Step 8 can be made crisper 

### ISSUE THREAD

**Issue by kanishk1010** [open-learning-exchange/open-learning-exchange.github.io#839]
Would be clearer to the intern if it is presented in a way that it is an extension of task 6.

**Comment by aurinsomnia** [comment]
@kanishk1010 I think similar to #838 this is somewhat debatable, as the step does literally say "You will follow the same steps as in GitHub Issues, but will be working to improve this Markdown Wiki so that it is clearer and better for future use." That said, this process is about improving the wiki however you think is best, so if you think the phrasing can be improved and through that bring greater clarity to the page, very well. Just like #838, I'll assign this to you, with the caveat that the changes all depend on whether you feel you can rephrase the page or somehow reformat it to improve it. If you do so, and articulate why the change is better, than we can absolutely pull the changes.

**Comment by kanishk1010** [comment]
@aurinsomnia Thank you for the feedback. You are right. But I think it also leaves it open to a different interpretation.

 "You will follow the same steps as in GitHub Issues, but will be working to improve this Markdown Wiki so that it is clearer and better for future use." might, prima facie,  look like one has to follow the same guideline "but" this time has to do something different than before.
It does refer to the the general 'Github Issues' guideline but not to the 'task' in step 6 (which is also about improving the wiki). 

I would modify the text as follows:

Create three *more* issues, add comments to three other issues, and resolve three issues by making the necessary changes in your repo with three separate pull requests. You will follow the same steps as in GitHub Issues, but will be working to improve this Markdown Wiki *, much the same as step 6,* so that it is clearer and better for future use. As you have now followed along with the Markdown Wiki thus far, you should all try to improve the clarity of the explanations for these steps. Learn by teaching - or editing our teaching tool, in this case! When you are fixing an issue, mention the number of the issue you are fixing in the description of your pull request.

P.S. I have also created an issue to mention 'the task' explicitly in step 6.

I would create a pull request, in case this change is deemed desirable.

**Comment by aurinsomnia** [comment]
@kanishk1010 This looks good to me, well-written and clear. Go ahead and make a Pull Request!

**Comment by kanishk1010** [comment]
@aurinsomnia glad you liked it. Created a pull request #848
