### ISSUE TITLE
Create numbered, step by step workflows on Git Repositories when apporpriate

### ISSUE THREAD

**Issue by alexkarasik** [open-learning-exchange/open-learning-exchange.github.io#857]
At the bottom of each section, I think it would be useful to layout the workflow and most of the commands in a step-by-step process as much as possible.

**Comment by alexkarasik** [comment]
It would look something like this:

Make sure you are synced up properly to the upstream repository at the beginning of every session with the following commands:
1. git fetch upstream
2. git checkout master - *should get a message that your branch is up to date*
3. git merge upstream/master

**Comment by sarah-lu102** [comment]
@alexkarasik what do you mean by each section?

**Comment by alexkarasik** [comment]
Each step is broken up into issues, like "Create an Issue", "Create a Commit", "Create a Pull Request". A step by step summary at the end of each section would nicely summarize the already described steps.

**Comment by sarah-lu102** [comment]
ok! You can make a pull request for this so we can see what edits you were thinking of - make sure to include the issue number and a link to the issue in your PR description. 

For future issues, we also recommend that you put a link that refers to the section that you want to change so that it is easier for others to see where you want to make your changes. For example in this issue description, I would use markdown to direct readers to [this location](http://open-learning-exchange.github.io/#!./pages/githubissues.md)

**Comment by ChenjieZhou** [comment]
@alexkarasik Totally agree. And it would be more clear if separate how to use Github, how to write Markdown and how to operate BeLL.
