### ISSUE TITLE
Clarify GitHub setting in takeHomeAndroidStudioSetup.md

### ISSUE THREAD

**Issue by Yurockkk** [open-learning-exchange/open-learning-exchange.github.io#870]
I found myself a little confused about GitHub setting while following [Android Studio Setup](http://open-learning-exchange.github.io/#!./pages/takeHomeAndroidStudioSetup.md). To make Take-Home setup process clearer, we can add a little more contents about GitHub setting in takeHomeAndroidStudioSetup.md. I might add a list somewhere in the page.

1. Find and fork the correct repository
2. Clone your GitHub repository username / take-home
3. Configure a remote for your local repository

In addition, the title of [Android Studio Setup page](http://open-learning-exchange.github.io/#!./pages/takeHomeAndroidStudioSetup.md) doesn’t look right. It should be “Android Studio Setup” instead of “OLE | Virtual interns”

![screen shot 2017-06-10 at 12 18 53 pm](https://user-images.githubusercontent.com/11954766/27004426-10a40f60-4dd7-11e7-83b3-bbde7d52b3bd.png)

**Comment by kylemathias** [comment]
i think the "OLE | Virtual interns" is site wide and is still fine for us because we are technical all interns. If you wanted to, you could add the steps for the GitHub cloning and forking steps.

EDIT: i just noticed the tab heading changes with what we are looking at. I really dont know how to go about fixing that. if you can find a way, that would be great.

**Comment by Yurockkk** [comment]
@kylemathias I'll make a PR for the issue

**Comment by Yurockkk** [comment]
@kylemathias Done. look at [here](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/877)
