### ISSUE TITLE
Update how to preview on Windows in README.md

### ISSUE THREAD

**Issue by LKhadka** [open-learning-exchange/open-learning-exchange.github.io#895]
Text editors like Brackets and VS Code and Atom (with extensions) can live reload static files on the fly. I have been using VS Code to edit and preview changes locally on Ubuntu and Windows.

**Comment by kylemathias** [comment]
Could you explain this issue a little more for us?

**Comment by LKhadka** [comment]
It's from the how to preview section of the README. I think information about text editors can be added in this section.
![image](https://user-images.githubusercontent.com/6295956/27199122-805e16fa-51da-11e7-84af-588813f5e638.png)

**Comment by kylemathias** [comment]
This might be a preference change. You could add something about "Hey you can use an editor like:_____" that would be fine, but using the rawgit and GitHub editor is what most of us use because its a true view on how it will be displayed. If you want to make the change, go ahead, if you don't think it would be a good idea in light of this new information, go ahead and close this out.

**Comment by LKhadka** [comment]
I guess it would be better for newcomers to get used to GitHub editor rather than that but I think it would be okay to add a small info about editors so that they can work when they do not have internet.

**Comment by sagun98** [comment]
@LKhadka  Adding other editors in the README file seems like a good idea.
