### ISSUE TITLE
FAQ page inconsistent in smaller screens (mobile devices)

### ISSUE THREAD

**Issue by sagun98** [open-learning-exchange/open-learning-exchange.github.io#897]
There is horizontal scrolling in FAQ page. This problem is due to the long links in the body of the page.  
![faq](https://user-images.githubusercontent.com/15079734/27150316-5f80d1f8-510c-11e7-9df9-31035b8f4279.png)

**Comment by kylemathias** [comment]
The screen size you are show is extremely small. I just tested it on my phone and this is what it looks like on a galaxy s7:
![screenshot_20170615-124601 1156](https://user-images.githubusercontent.com/26488295/27198901-f9e7a1b0-51c8-11e7-9ddd-7967555d7c9c.png)

I dont think this issue is top priority right now.

**Comment by sagun98** [comment]
@kylemathias  Gotcha !! I ll close this issue for now.
