### ISSUE TITLE
Trouble Shooting Wiki Suggestion

### ISSUE THREAD

**Issue by epistulae** [open-learning-exchange/open-learning-exchange.github.io#93]
I think it would be helpful to have another subsection of the wiki for troubleshooting. 
It would be something akin to an FAQ for common problems people have run into, and problems that have discussed in the chat. This way everyone can have a place to view a compilation of past errors, and perhaps help with their own troubleshooting.

**Comment by sthak004** [comment]
This seems like a good idea! I just think we need to refine the idea a bit. 

Here are my concerns:

1. In most cases, there are multiple approaches to a problem. So, if we were to have a page with common issues, then the list would scale to a potentially unmanageable rate with any one problem having several different approaches and all of which may need to be updated if there is a global change to the platform.
2. With the exception of this issues page where, once an issue is closed, it is no longer available to see, the FAQ page you mention and the issues page are in some sense, identical. This would lead us to having 2 different pages with replicated information. The reason I say this is because we are given the task of commenting on at least three issues in hopes of familiarizing ourselves with this page (i.e. to keep checking this page for issues that other people have, in hope to either help them resolve a problem or get updated on an issue that you might run into in the future). So, if we are encouraged to look on a page regularly where other people can post potentially relatable issues, then I believe it serves the same purpose.


I still believe this a good idea but, I just feel like if we tailor the page to problems that we could foresee regardless of updating the platform, then it might seem a bit more feasible. I could very well be wrong in my approach but, these are just some of the potential drawbacks to the idea I see.

**Comment by EmilyLarkin** [comment]
@DrewPerlman this might be helpful for you! Hint: @DrewPerlman is working on an FAQ section of the MDwiki so feel free include more concerns here.

**Comment by aberdean** [comment]
No longer relevant (FAQ page was already created).
